import { styles as common } from '../../styles/common.styles';

export const styles = {
  form: {
    backgroundColor: '#13131A',
    border: '1px solid #2A2A3D',
    borderRadius: '20px',
    padding: '2.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '0',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
    padding: '0.5rem 0 1.5rem',
  },
  sectionLabel: {
    ...common.sectionLabel,
    color: '#FF2E63',
    margin: 0,
  },
  divider: {
    height: '1px',
    backgroundColor: '#1C1C28',
    margin: '0.5rem 0 1.5rem',
  },
  textarea: {
    ...common.input,
    resize: 'vertical',
    fontFamily: "'Inter', sans-serif",
    lineHeight: 1.6,
  },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  imagePreview: {
    width: '100%',
    height: '200px',
    objectFit: 'cover',
    borderRadius: '10px',
    border: '1px solid #2A2A3D',
  },
  submitBtn: {
    background: 'linear-gradient(135deg, #FF2E63, #e0196b)',
    color: '#fff',
    border: 'none',
    borderRadius: '12px',
    padding: '1rem',
    fontWeight: 900,
    fontSize: '0.95rem',
    cursor: 'pointer',
    marginTop: '1rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    width: '100%',
  },

  success: {
    backgroundColor: '#13131A',
    border: '1px solid #2A2A3D',
    borderRadius: '20px',
    padding: '4rem 2rem',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '0.75rem',
    textAlign: 'center',
  },
  successIcon: {
    fontSize: '3rem',
    marginBottom: '0.5rem',
  },
  successTitle: {
    fontSize: '1.4rem',
    fontWeight: 900,
    color: '#EAEAEA',
  },
  successSub: {
    fontSize: '0.95rem',
    color: '#4A4A6A',
    marginBottom: '1rem',
  },
  successBtn: {
    background: 'none',
    border: '1px solid #2A2A3D',
    borderRadius: '10px',
    color: '#EAEAEA',
    padding: '0.7rem 2rem',
    fontSize: '0.85rem',
    cursor: 'pointer',
    letterSpacing: '0.08em',
  },
};
