export const styles = {
  form: {
    backgroundColor: '#13131A',
    border: '1px solid #2A2A3D',
    borderRadius: '16px',
    padding: '2rem',
    maxWidth: '560px',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.4rem',
  },
  label: {
    fontSize: '0.72rem',
    fontWeight: 700,
    color: '#4A4A6A',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  input: {
    backgroundColor: '#0B0B0F',
    border: '1px solid #2A2A3D',
    borderRadius: '8px',
    padding: '0.75rem 1rem',
    color: '#EAEAEA',
    fontSize: '0.95rem',
    width: '100%',
    boxSizing: 'border-box',
  },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  submitBtn: {
    background: 'linear-gradient(135deg, #FF2E63, #e0196b)',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    padding: '0.95rem',
    fontWeight: 700,
    fontSize: '0.85rem',
    cursor: 'pointer',
    marginTop: '0.5rem',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
  },
  success: {
    backgroundColor: 'rgba(255,46,99,0.08)',
    border: '1px solid rgba(255,46,99,0.4)',
    borderRadius: '12px',
    padding: '1.2rem 1.5rem',
    color: '#FF2E63',
    fontSize: '0.95rem',
    textAlign: 'center',
    maxWidth: '560px',
  },
};
