export const styles = {
  page: {
    minHeight: '100vh',
    fontFamily: "'Inter', sans-serif",
    backgroundColor: '#0B0B0F',
    color: '#EAEAEA',
    position: 'relative',
    overflow: 'hidden',
  },
  inner: {
    maxWidth: '780px',
    margin: '0 auto',
    padding: '2rem 2rem 6rem',
    position: 'relative',
    zIndex: 1,
  },
  header: {
    textAlign: 'center',
    marginBottom: '3rem',
    paddingTop: '1rem',
  },
  eyebrow: {
    fontSize: '0.72rem',
    fontWeight: 700,
    letterSpacing: '0.2em',
    textTransform: 'uppercase',
    color: '#4A4A6A',
    marginBottom: '0.75rem',
  },
  heading: {
    fontSize: '3rem',
    fontWeight: 900,
    letterSpacing: '-0.03em',
    lineHeight: 1.1,
    margin: '0 0 1rem',
  },
  sub: {
    fontSize: '1rem',
    color: '#4A4A6A',
    margin: 0,
  },
  backBtn: {
    background: 'rgba(255,255,255,0.05)',
    border: '1px solid rgba(255,255,255,0.1)',
    color: '#EAEAEA',
    borderRadius: '8px',
    padding: '0.5rem 1rem',
    fontSize: '0.85rem',
    cursor: 'pointer',
    marginBottom: '2rem',
    display: 'inline-block',
  },
};
