import { styles as common } from '../../styles/common.styles';

export const styles = {
  page: {
    ...common.page,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '3rem 2rem',
    position: 'relative',
    overflow: 'hidden',
  },
  inner: {
    width: '100%',
    maxWidth: '760px',
    position: 'relative',
    zIndex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  eyebrow: { ...common.eyebrow, marginBottom: '0.5rem', textAlign: 'center' },
  heading: {
    fontSize: '2.2rem',
    fontWeight: 900,
    textAlign: 'center',
    marginBottom: '2.5rem',
    letterSpacing: '-0.02em',
  },

  ticket: {
    width: '100%',
    display: 'flex',
    borderRadius: '20px',
    overflow: 'hidden',
    position: 'relative',
    boxShadow: '0 30px 80px rgba(0,0,0,0.7), 0 0 0 1px rgba(255,255,255,0.07)',
  },
  bgImage: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    opacity: 0.07,
    pointerEvents: 'none',
    zIndex: 0,
  },

  stub: {
    flexShrink: 0,
    width: '110px',
    backgroundColor: '#FF2E63',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem 1rem',
    gap: '0.4rem',
    position: 'relative',
    zIndex: 1,
  },
  stubDate: {
    fontSize: '1.8rem',
    fontWeight: 900,
    color: '#fff',
    lineHeight: 1,
  },
  stubYear: {
    fontSize: '0.75rem',
    color: 'rgba(255,255,255,0.7)',
    fontWeight: 600,
  },
  stubDivider: {
    width: '40px',
    height: '1px',
    backgroundColor: 'rgba(255,255,255,0.3)',
    margin: '0.6rem 0',
  },
  stubSeat: {
    fontSize: '1.4rem',
    fontWeight: 900,
    color: '#fff',
  },
  stubSeatLabel: {
    fontSize: '0.6rem',
    color: 'rgba(255,255,255,0.65)',
    textAlign: 'center',
    lineHeight: 1.4,
    textTransform: 'uppercase',
    letterSpacing: '0.08em',
  },

  perforation: {
    flexShrink: 0,
    width: '20px',
    backgroundColor: '#13131A',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    zIndex: 1,
  },
  circleTop: {
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    backgroundColor: '#0B0B0F',
    flexShrink: 0,
    marginTop: '-1px',
  },
  dashedLine: {
    flex: 1,
    borderLeft: '2px dashed rgba(255,255,255,0.1)',
  },
  circleBottom: {
    width: '20px',
    height: '20px',
    borderRadius: '50%',
    backgroundColor: '#0B0B0F',
    flexShrink: 0,
    marginBottom: '-1px',
  },

  body: {
    flex: 1,
    backgroundColor: '#13131A',
    padding: '2rem 2rem 1.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1rem',
    position: 'relative',
    zIndex: 1,
  },
  bodyTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  genre: {
    fontSize: '0.65rem',
    fontWeight: 700,
    letterSpacing: '0.18em',
    textTransform: 'uppercase',
    color: '#4A4A6A',
  },
  badge: {
    fontSize: '0.7rem',
    fontWeight: 700,
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    backgroundColor: 'rgba(255,46,99,0.15)',
    color: '#FF2E63',
    border: '1px solid rgba(255,46,99,0.3)',
    borderRadius: '999px',
    padding: '0.25rem 0.75rem',
  },
  title: {
    fontSize: '1.9rem',
    fontWeight: 900,
    color: '#EAEAEA',
    lineHeight: 1.1,
    letterSpacing: '-0.02em',
    margin: 0,
  },
  metaRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
    marginTop: '0.25rem',
  },
  metaItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.2rem',
  },
  metaLabel: { ...common.sectionLabel, fontSize: '0.62rem', letterSpacing: '0.15em' },
  metaValue: {
    fontSize: '0.9rem',
    fontWeight: 600,
    color: '#EAEAEA',
  },
  metaValueAccent: {
    fontSize: '0.9rem',
    fontWeight: 700,
    color: '#FF2E63',
  },

  ticketFooter: {
    borderTop: '1px solid #1C1C28',
    paddingTop: '1rem',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '1rem',
    marginTop: 'auto',
  },
  barcode: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: '2px',
    height: '36px',
  },
  bar: {
    backgroundColor: '#EAEAEA',
    height: '100%',
    borderRadius: '1px',
  },
  ticketNumber: {
    fontSize: '0.7rem',
    fontWeight: 700,
    letterSpacing: '0.18em',
    color: '#4A4A6A',
    textTransform: 'uppercase',
  },

  form: {
    width: '100%',
    backgroundColor: '#13131A',
    border: '1px solid #2A2A3D',
    borderRadius: '20px',
    padding: '2rem',
    marginTop: '1.5rem',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
  },
  formTitle: { ...common.sectionLabel, margin: 0 },
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  formFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTop: '1px solid #1C1C28',
    paddingTop: '1.2rem',
    gap: '1rem',
    marginTop: '0.4rem',
  },
  total: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.2rem',
  },
  totalLabel: { ...common.sectionLabel, fontSize: '0.65rem', letterSpacing: '0.15em' },
  totalValue: {
    fontSize: '2rem',
    fontWeight: 900,
    color: '#FF2E63',
    lineHeight: 1,
  },
  buyBtn: {
    background: 'linear-gradient(135deg, #FF2E63, #e0196b)',
    color: '#fff',
    border: 'none',
    borderRadius: '12px',
    padding: '1rem 2.5rem',
    fontWeight: 900,
    fontSize: '1rem',
    cursor: 'pointer',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
};
