import { styles as common } from '../../styles/common.styles';
import { colors, fontSize, fontWeight, borderRadius, zIndex } from '../../styles/tokens';

export const styles = {
  page: {
    ...common.page,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 32px',
    position: 'relative',
    overflow: 'hidden',
  },
  inner: {
    width: '100%',
    maxWidth: '760px',
    position: 'relative',
    zIndex: zIndex.raised,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
  },
  eyebrow: { ...common.eyebrow, marginBottom: '8px', textAlign: 'center' },
  heading: {
    fontSize: fontSize.display2,
    fontWeight: fontWeight.black,
    textAlign: 'center',
    marginBottom: '40px',
    letterSpacing: '-0.02em',
  },

  ticket: {
    width: '100%',
    display: 'flex',
    borderRadius: borderRadius.xxl,
    overflow: 'hidden',
    position: 'relative',
    boxShadow: '0 30px 80px rgba(0,0,0,0.7), 0 0 0 1px rgba(255,255,255,0.07)',
  },
  bgImage: {
    position: 'absolute',
    inset: 0,
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    opacity: 0.07,
    pointerEvents: 'none',
    zIndex: zIndex.base,
  },

  stub: {
    flexShrink: 0,
    width: '110px',
    backgroundColor: colors.primary,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px 16px',
    gap: '6px',
    position: 'relative',
    zIndex: zIndex.raised,
  },
  stubDate: {
    fontSize: fontSize.xl9,
    fontWeight: fontWeight.black,
    color: colors.textWhite,
    lineHeight: 1,
  },
  stubYear: {
    fontSize: fontSize.base,
    color: colors.whiteSoft,
    fontWeight: fontWeight.semibold,
  },
  stubDivider: {
    width: '40px',
    height: '1px',
    backgroundColor: colors.whiteMuted,
    margin: '10px 0',
  },
  stubSeat: {
    fontSize: fontSize.xl7,
    fontWeight: fontWeight.black,
    color: colors.textWhite,
  },
  stubSeatLabel: {
    fontSize: fontSize.xs,
    color: colors.whiteLight,
    textAlign: 'center',
    lineHeight: 1.4,
    textTransform: 'uppercase',
    letterSpacing: '1.3px',
  },

  perforation: {
    flexShrink: 0,
    width: '20px',
    backgroundColor: colors.bgCard,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    zIndex: zIndex.raised,
  },
  circleTop: {
    width: '20px',
    height: '20px',
    borderRadius: borderRadius.circle,
    backgroundColor: colors.bgBase,
    flexShrink: 0,
    marginTop: '-1px',
  },
  dashedLine: {
    flex: 1,
    borderLeft: '2px dashed rgba(255,255,255,0.1)',
  },
  circleBottom: {
    width: '20px',
    height: '20px',
    borderRadius: borderRadius.circle,
    backgroundColor: colors.bgBase,
    flexShrink: 0,
    marginBottom: '-1px',
  },

  body: {
    flex: 1,
    backgroundColor: colors.bgCard,
    padding: '32px 32px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    position: 'relative',
    zIndex: zIndex.raised,
  },
  bodyTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  genre: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: '2.9px',
    textTransform: 'uppercase',
    color: colors.textSecondary,
  },
  badge: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    letterSpacing: '1.6px',
    textTransform: 'uppercase',
    backgroundColor: colors.primaryBg,
    color: colors.primary,
    border: `1px solid ${colors.primaryBorder}`,
    borderRadius: borderRadius.full,
    padding: '4px 12px',
  },
  title: {
    fontSize: fontSize.xl10,
    fontWeight: fontWeight.black,
    color: colors.textPrimary,
    lineHeight: 1.1,
    letterSpacing: '-0.02em',
    margin: 0,
  },
  metaRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
    marginTop: '4px',
  },
  metaItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  metaLabel: { ...common.sectionLabel, fontSize: fontSize.xs, letterSpacing: '2.4px' },
  metaValue: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.semibold,
    color: colors.textPrimary,
  },
  metaValueAccent: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.bold,
    color: colors.primary,
  },

  ticketFooter: {
    borderTop: `1px solid ${colors.borderSubtle}`,
    paddingTop: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    marginTop: 'auto',
  },
  barcode: {
    display: 'flex',
    alignItems: 'flex-end',
    gap: '2px',
    height: '36px',
  },
  bar: {
    backgroundColor: colors.textPrimary,
    height: '100%',
    borderRadius: borderRadius.xs,
  },
  ticketNumber: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    letterSpacing: '2.9px',
    color: colors.textSecondary,
    textTransform: 'uppercase',
  },

  form: {
    width: '100%',
    backgroundColor: colors.bgCard,
    border: `1px solid ${colors.borderDefault}`,
    borderRadius: borderRadius.xxl,
    padding: '32px',
    marginTop: '24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '19px',
  },
  formTitle: { ...common.sectionLabel, margin: 0 },
  formRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
  },
  formFooter: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTop: `1px solid ${colors.borderSubtle}`,
    paddingTop: '19px',
    gap: '16px',
    marginTop: '6px',
  },
  total: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  totalLabel: { ...common.sectionLabel, fontSize: fontSize.xs, letterSpacing: '2.4px' },
  totalValue: {
    fontSize: fontSize.display1,
    fontWeight: fontWeight.black,
    color: colors.primary,
    lineHeight: 1,
  },
  buyBtn: {
    background: `linear-gradient(135deg, ${colors.primary}, ${colors.primaryDark})`,
    color: colors.textWhite,
    border: 'none',
    borderRadius: borderRadius.lg,
    padding: '16px 40px',
    fontWeight: fontWeight.black,
    fontSize: fontSize.xl2,
    cursor: 'pointer',
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
};
