import { styles as common } from '../../styles/common.styles';
import { colors, fontSize, fontWeight, borderRadius, zIndex } from '../../styles/tokens';

export const styles = {
  page: {
    ...common.page,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '48px 24px',
    position: 'relative',
    overflow: 'hidden',
  },
  inner: {
    width: '100%',
    maxWidth: '480px',
    position: 'relative',
    zIndex: zIndex.raised,
  },

  header: {
    textAlign: 'center',
    marginBottom: '32px',
  },
  eyebrow: { ...common.eyebrow, marginBottom: '12px' },
  heading: {
    fontSize: fontSize.display2,
    fontWeight: fontWeight.black,
    letterSpacing: '-0.02em',
    lineHeight: 1.1,
    margin: '0 0 8px',
    color: colors.textPrimary,
  },
  sub: {
    fontSize: fontSize.lg,
    color: colors.textSecondary,
    margin: 0,
  },

  scanSection: {
    backgroundColor: colors.bgCard,
    border: `1px solid ${colors.borderDefault}`,
    borderRadius: borderRadius.xl,
    padding: '32px',
    textAlign: 'center',
    marginBottom: '16px',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '16px',
  },
  scanLabel: { ...common.sectionLabel },
  scanPlaceholder: {
    width: '160px',
    height: '160px',
    border: `2px dashed ${colors.borderDefault}`,
    borderRadius: borderRadius.lg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    letterSpacing: '1.6px',
    textTransform: 'uppercase',
  },
  scanBtn: {
    background: `linear-gradient(135deg, ${colors.primary}, ${colors.primaryDark})`,
    color: colors.textWhite,
    border: 'none',
    borderRadius: borderRadius.lg,
    padding: '12px 28px',
    fontWeight: fontWeight.black,
    fontSize: fontSize.base,
    cursor: 'pointer',
    letterSpacing: '1.6px',
    textTransform: 'uppercase',
  },
  scannedId: {
    fontSize: fontSize.sm,
    color: colors.textSecondary,
    letterSpacing: '1.3px',
    fontFamily: 'monospace',
  },

  form: {
    backgroundColor: colors.bgCard,
    border: `1px solid ${colors.borderDefault}`,
    borderRadius: borderRadius.xl,
    padding: '28px 32px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
  },
  formTitle: { ...common.sectionLabel, marginBottom: '4px' },
  fieldGroup: { ...common.fieldGroup },
  label: { ...common.label },
  input: { ...common.input },

  submitBtn: {
    background: `linear-gradient(135deg, ${colors.primary}, ${colors.primaryDark})`,
    color: colors.textWhite,
    border: 'none',
    borderRadius: borderRadius.lg,
    padding: '14px 24px',
    fontWeight: fontWeight.black,
    fontSize: fontSize.xl2,
    cursor: 'pointer',
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
    width: '100%',
    marginTop: '4px',
  },
  submitBtnDisabled: {
    opacity: 0.5,
    cursor: 'not-allowed',
  },

  resultValid: {
    marginTop: '16px',
    backgroundColor: 'rgba(8,217,214,0.1)',
    border: `1px solid rgba(8,217,214,0.3)`,
    borderRadius: borderRadius.xl,
    padding: '20px 24px',
    textAlign: 'center',
    color: colors.secondary,
    fontWeight: fontWeight.bold,
    fontSize: fontSize.xl2,
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
  },
  resultInvalid: {
    marginTop: '16px',
    backgroundColor: colors.primaryBg,
    border: `1px solid ${colors.primaryBorder}`,
    borderRadius: borderRadius.xl,
    padding: '20px 24px',
    textAlign: 'center',
    color: colors.primary,
    fontWeight: fontWeight.bold,
    fontSize: fontSize.xl2,
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
  },
  resultError: {
    marginTop: '16px',
    backgroundColor: colors.primaryBg,
    border: `1px solid ${colors.primaryBorder}`,
    borderRadius: borderRadius.xl,
    padding: '16px 24px',
    color: colors.primary,
    fontSize: fontSize.base,
  },
};
