export const styles = {
  page: {
    minHeight: '100vh',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    backgroundColor: '#0f172a',
    color: '#f8fafc',
    padding: '2rem 3rem',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '2.5rem',
  },
  back: {
    background: 'none',
    border: '1px solid #334155',
    color: '#94a3b8',
    borderRadius: '8px',
    padding: '0.4rem 0.9rem',
    cursor: 'pointer',
    fontSize: '0.9rem',
  },
  title: {
    fontSize: '1.6rem',
    fontWeight: '800',
    color: '#f1f5f9',
    margin: 0,
  },
  grid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))',
    gap: '1.5rem',
  },
  card: {
    backgroundColor: '#1e293b',
    border: '1px solid #334155',
    borderRadius: '14px',
    overflow: 'hidden',
  },
  cardBanner: {
    height: '120px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '3rem',
    backgroundColor: '#1a1f35',
  },
  cardBody: {
    padding: '1.2rem',
  },
  cardTitle: {
    fontSize: '1rem',
    fontWeight: '700',
    marginBottom: '0.3rem',
    color: '#f1f5f9',
  },
  cardMeta: {
    fontSize: '0.82rem',
    color: '#64748b',
    marginBottom: '1rem',
    lineHeight: 1.6,
  },
  cardFooter: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  price: {
    fontSize: '1.1rem',
    fontWeight: '700',
    color: '#a5b4fc',
  },
  buyBtn: {
    backgroundColor: '#6366f1',
    color: '#fff',
    border: 'none',
    borderRadius: '7px',
    padding: '0.45rem 1rem',
    fontWeight: '700',
    fontSize: '0.85rem',
    cursor: 'pointer',
  },
};
