export const styles = {
  page: {
    minHeight: '100vh',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    backgroundColor: '#0f172a',
    color: '#f8fafc',
    padding: '2rem 3rem',
  },
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '2.5rem',
  },
  back: {
    background: 'none',
    border: '1px solid #334155',
    color: '#94a3b8',
    borderRadius: '8px',
    padding: '0.4rem 0.9rem',
    cursor: 'pointer',
    fontSize: '0.9rem',
  },
  title: {
    fontSize: '1.6rem',
    fontWeight: '800',
    color: '#f1f5f9',
    margin: 0,
  },
  form: {
    backgroundColor: '#1e293b',
    border: '1px solid #334155',
    borderRadius: '16px',
    padding: '2rem',
    maxWidth: '560px',
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
  },
  fieldGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '0.4rem',
  },
  label: {
    fontSize: '0.85rem',
    fontWeight: '600',
    color: '#94a3b8',
  },
  input: {
    backgroundColor: '#0f172a',
    border: '1px solid #334155',
    borderRadius: '8px',
    padding: '0.65rem 0.9rem',
    color: '#f1f5f9',
    fontSize: '0.95rem',
    outline: 'none',
    width: '100%',
    boxSizing: 'border-box',
  },
  row: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '1rem',
  },
  submitBtn: {
    backgroundColor: '#6366f1',
    color: '#fff',
    border: 'none',
    borderRadius: '10px',
    padding: '0.85rem',
    fontWeight: '700',
    fontSize: '1rem',
    cursor: 'pointer',
    marginTop: '0.5rem',
  },
  success: {
    backgroundColor: '#052e16',
    border: '1px solid #166534',
    borderRadius: '10px',
    padding: '1rem 1.5rem',
    color: '#4ade80',
    fontSize: '0.95rem',
    textAlign: 'center',
    maxWidth: '560px',
  },
};
