export const styles = {
  page: {
    minHeight: '100vh',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    backgroundColor: '#0f172a',
    color: '#f8fafc',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '2rem',
  },
  logo: {
    fontSize: '1.6rem',
    fontWeight: '800',
    color: '#6366f1',
    marginBottom: '0.5rem',
    letterSpacing: '-0.5px',
  },
  subtitle: {
    color: '#64748b',
    fontSize: '0.95rem',
    marginBottom: '3.5rem',
  },
  cards: {
    display: 'flex',
    gap: '2rem',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  card: {
    backgroundColor: '#1e293b',
    border: '1px solid #334155',
    borderRadius: '16px',
    padding: '2.5rem 2rem',
    width: '240px',
    textAlign: 'center',
  },
  cardIcon: {
    fontSize: '3rem',
    marginBottom: '1.2rem',
  },
  cardTitle: {
    fontSize: '1.15rem',
    fontWeight: '700',
    marginBottom: '0.6rem',
    color: '#f1f5f9',
  },
  cardDesc: {
    fontSize: '0.85rem',
    color: '#64748b',
    lineHeight: 1.6,
  },
  cardBtnBuy: {
    marginTop: '1.5rem',
    width: '100%',
    padding: '0.7rem',
    borderRadius: '8px',
    border: 'none',
    backgroundColor: '#6366f1',
    color: '#fff',
    fontWeight: '700',
    fontSize: '0.95rem',
    cursor: 'pointer',
  },
  cardBtnCreate: {
    marginTop: '1.5rem',
    width: '100%',
    padding: '0.7rem',
    borderRadius: '8px',
    border: '1px solid #6366f1',
    backgroundColor: 'transparent',
    color: '#a5b4fc',
    fontWeight: '700',
    fontSize: '0.95rem',
    cursor: 'pointer',
  },
};
