export const styles = {
  card: {
    backgroundColor: '#13131A',
    border: '1px solid #2A2A3D',
    borderRadius: '16px',
    overflow: 'hidden',
  },
  banner: {
    height: '160px',
    position: 'relative',
    overflow: 'hidden',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
    transition: 'transform 0.4s ease',
  },
  bannerOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(to top, rgba(11,11,15,0.65) 0%, transparent 60%)',
  },
  body: { padding: '1.2rem' },
  title: {
    fontSize: '1rem',
    fontWeight: 700,
    color: '#EAEAEA',
    marginBottom: '0.3rem',
  },
  meta: {
    fontSize: '0.78rem',
    color: '#4A4A6A',
    marginBottom: '1rem',
    lineHeight: 1.7,
  },
  footer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  price: {
    fontSize: '1.15rem',
    fontWeight: 900,
    color: '#FF2E63',
  },
  buyBtn: {
    background: 'linear-gradient(135deg, #FF2E63, #e0196b)',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '0.5rem 1.2rem',
    fontWeight: 700,
    fontSize: '0.78rem',
    cursor: 'pointer',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
};
