export const styles = {
  card: {
    backgroundColor: '#13131A',
    border: '1px solid #2A2A3D',
    borderRadius: '16px',
    overflow: 'hidden',
  },
  banner: {
    height: '130px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '3.2rem',
    background: 'linear-gradient(135deg, #1C1C28 0%, #0B0B0F 100%)',
    position: 'relative',
  },
  bannerOverlay: {
    position: 'absolute',
    inset: 0,
    background: 'linear-gradient(to top, rgba(0,0,0,0.4), transparent)',
  },
  bannerEmoji: { position: 'relative', zIndex: 1 },
  body: { padding: '1.2rem' },
  title: {
    fontSize: '1rem',
    fontWeight: 700,
    color: '#EAEAEA',
    marginBottom: '0.3rem',
  },
  meta: {
    fontSize: '0.78rem',
    color: '#4A4A6A',
    marginBottom: '1rem',
    lineHeight: 1.7,
  },
  footer: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  price: {
    fontSize: '1.15rem',
    fontWeight: 900,
    color: '#FF2E63',
  },
  buyBtn: {
    background: 'linear-gradient(135deg, #FF2E63, #e0196b)',
    color: '#fff',
    border: 'none',
    borderRadius: '8px',
    padding: '0.5rem 1.2rem',
    fontWeight: 700,
    fontSize: '0.78rem',
    cursor: 'pointer',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
};
