import { colors, fontSize, fontWeight, borderRadius } from '../../styles/tokens';

export const styles = {
  card: {
    backgroundColor: colors.bgCard,
    border: `1px solid ${colors.borderDefault}`,
    borderRadius: borderRadius.xl,
    overflow: 'hidden',
    cursor: 'pointer',
  },
  banner: {
    height: '200px',
    position: 'relative',
    overflow: 'hidden',
  },
  image: {
    width: '100%',
    height: '100%',
    objectFit: 'cover',
    display: 'block',
    transition: 'transform 0.4s ease',
  },
  bannerOverlay: {
    position: 'absolute',
    inset: 0,
    background: `linear-gradient(to top, ${colors.overlayDark} 0%, ${colors.overlayLight} 60%, transparent 100%)`,
  },
  body: {
    padding: '19px 22px 22px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: '16px',
  },
  info: { flex: 1, minWidth: 0 },
  title: {
    fontSize: fontSize.xl3,
    fontWeight: fontWeight.bold,
    color: colors.textPrimary,
    marginBottom: '6px',
    whiteSpace: 'nowrap',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
  },
  meta: {
    fontSize: fontSize.md,
    color: colors.textSecondary,
    lineHeight: 1.75,
  },
  price: {
    fontSize: fontSize.xl5,
    fontWeight: fontWeight.black,
    color: colors.primary,
    flexShrink: 0,
  },
  soldOutBadge: {
    position: 'absolute',
    top: '12px',
    right: '12px',
    backgroundColor: colors.primary,
    color: colors.textWhite,
    borderRadius: borderRadius.full,
    padding: '4px 12px',
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    letterSpacing: '1.6px',
    textTransform: 'uppercase',
    zIndex: 1,
  },
  priceSoldOut: {
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    color: colors.textSecondary,
    flexShrink: 0,
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
  },
};
