export const styles = {
  page: {
    minHeight: '100vh',
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    backgroundColor: '#0f172a',
    color: '#f8fafc',
    backgroundImage: 'radial-gradient(ellipse 80% 50% at 50% -10%, rgba(99,102,241,0.2), transparent)',
  },

  nav: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1.2rem 2.5rem',
    borderBottom: '1px solid #1e293b',
  },
  logo: {
    fontSize: '1rem',
    fontWeight: '700',
    color: '#a5b4fc',
    letterSpacing: '0.12em',
    textTransform: 'uppercase',
  },
  createBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
    backgroundColor: 'transparent',
    border: '1px solid #334155',
    color: '#cbd5e1',
    padding: '0.5rem 1.1rem',
    borderRadius: '10px',
    fontSize: '0.88rem',
    fontWeight: '600',
    cursor: 'pointer',
  },

  hero: {
    textAlign: 'center',
    padding: '5rem 2rem 3rem',
  },
  heroTitle: {
    fontSize: '3rem',
    fontWeight: '800',
    lineHeight: 1.15,
    margin: '0 0 0.8rem',
    background: 'linear-gradient(135deg, #f8fafc 30%, #a5b4fc 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  heroSub: {
    fontSize: '1rem',
    color: '#64748b',
    margin: '0 0 2rem',
  },

  searchWrap: {
    display: 'flex',
    maxWidth: '600px',
    margin: '0 auto',
    backgroundColor: '#1e293b',
    border: '1px solid #334155',
    borderRadius: '14px',
    overflow: 'hidden',
  },
  searchInput: {
    flex: 1,
    backgroundColor: 'transparent',
    border: 'none',
    outline: 'none',
    padding: '1rem 1.2rem',
    fontSize: '1rem',
    color: '#f1f5f9',
    minWidth: 0,
  },
  searchBtn: {
    backgroundColor: '#6366f1',
    border: 'none',
    color: '#fff',
    padding: '0 1.5rem',
    fontSize: '0.95rem',
    fontWeight: '700',
    cursor: 'pointer',
    borderRadius: '0 12px 12px 0',
    whiteSpace: 'nowrap',
  },

  results: {
    maxWidth: '680px',
    margin: '2rem auto',
    padding: '0 2rem 4rem',
  },
  resultsLabel: {
    fontSize: '0.8rem',
    color: '#475569',
    marginBottom: '1.2rem',
    letterSpacing: '0.05em',
    textTransform: 'uppercase',
  },
  grid: {
    display: 'flex',
    flexDirection: 'column',
    gap: '1.2rem',
  },
  card: {
    backgroundColor: '#131c2e',
    border: '1px solid #1e293b',
    borderRadius: '16px',
    overflow: 'hidden',
    cursor: 'pointer',
  },
  cardImage: {
    height: '180px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '4rem',
    position: 'relative',
  },
  cardBody: {
    padding: '1.2rem 1.4rem 1.4rem',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: '1rem',
  },
  cardInfo: {
    flex: 1,
    minWidth: 0,
  },
  cardTitle: {
    fontSize: '1.1rem',
    fontWeight: '700',
    color: '#f1f5f9',
    marginBottom: '0.4rem',
  },
  cardMeta: {
    fontSize: '0.82rem',
    color: '#475569',
    lineHeight: 1.7,
  },
  cardPrice: {
    fontSize: '1.3rem',
    fontWeight: '800',
    color: '#a5b4fc',
    flexShrink: 0,
  },

  empty: {
    textAlign: 'center',
    color: '#334155',
    padding: '3rem 0',
    fontSize: '1rem',
  },
};

// Per-concert gradient banners
export const bannerColors = [
  'linear-gradient(135deg, #1e1b4b 0%, #312e81 100%)',
  'linear-gradient(135deg, #1a1035 0%, #4c1d95 100%)',
  'linear-gradient(135deg, #0c1a2e 0%, #1e3a5f 100%)',
  'linear-gradient(135deg, #1a0a2e 0%, #6b21a8 100%)',
  'linear-gradient(135deg, #0f2027 0%, #203a43 50%, #2c5364 100%)',
  'linear-gradient(135deg, #1a0533 0%, #7e22ce 100%)',
];
