export const styles = {
  wrap: {
    display: 'flex',
    maxWidth: '620px',
    margin: '0 auto',
    backgroundColor: '#13131A',
    border: '1px solid #2A2A3D',
    borderRadius: '12px',
    overflow: 'hidden',
  },
  input: {
    flex: 1,
    minWidth: 0,
    backgroundColor: 'transparent',
    border: 'none',
    padding: '1rem 1.3rem',
    fontSize: '1rem',
    color: '#EAEAEA',
    outline: 'none',
  },
  btn: {
    background: 'linear-gradient(135deg, #FF2E63, #e0196b)',
    border: 'none',
    color: '#fff',
    padding: '0 2rem',
    fontSize: '0.8rem',
    fontWeight: 700,
    cursor: 'pointer',
    letterSpacing: '0.1em',
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  },
};
