import { colors, fontSize, fontWeight, borderRadius, zIndex } from '../../styles/tokens';

export const styles = {
  wrapper: {
    position: 'sticky',
    top: 0,
    zIndex: zIndex.navbar,
  },
  nav: {
    height: '64px',
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '16px 40px',
    backgroundColor: colors.bgNavbar,
    backdropFilter: 'blur(16px)',
    borderBottom: `1px solid ${colors.borderSubtle}`,
  },
  backBtn: {
    position: 'absolute',
    top: '100%',
    left: '40px',
    marginTop: '16px',
    backgroundColor: colors.bgNavbar,
    backdropFilter: 'blur(16px)',
    border: `1px solid ${colors.borderDefault}`,
    color: colors.textPrimary,
    borderRadius: borderRadius.sm,
    padding: '6px 14px',
    fontSize: fontSize.md,
    cursor: 'pointer',
  },
  links: {
    display: 'flex',
    gap: '4px',
    alignItems: 'center',
  },
  link: {
    background: 'none',
    border: 'none',
    color: colors.textSecondary,
    fontSize: fontSize.sm,
    fontWeight: fontWeight.semibold,
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
    cursor: 'pointer',
    padding: '6px 14px',
    borderRadius: borderRadius.sm,
    transition: 'color 0.15s',
  },
  linkActive: {
    color: colors.textPrimary,
    backgroundColor: colors.borderSubtle,
  },
  logo: {
    fontSize: fontSize.xl6,
    fontWeight: fontWeight.black,
    letterSpacing: '2.4px',
    textTransform: 'uppercase',
    cursor: 'pointer',
  },
  logoPrimary: { color: colors.primary },
  logoSecondary: { color: colors.secondary },
  createBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '6px',
    backgroundColor: 'transparent',
    border: `1px solid ${colors.secondary}`,
    color: colors.secondary,
    padding: '8px 19px',
    borderRadius: borderRadius.sm,
    fontSize: fontSize.md,
    fontWeight: fontWeight.bold,
    cursor: 'pointer',
    letterSpacing: '1.3px',
    textTransform: 'uppercase',
  },
};
