export const styles = {
  nav: {
    position: 'sticky',
    top: 0,
    zIndex: 50,
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '1rem 2.5rem',
    backgroundColor: 'rgba(11,11,15,0.92)',
    backdropFilter: 'blur(16px)',
    borderBottom: '1px solid #1C1C28',
  },
  logo: {
    fontSize: '1.3rem',
    fontWeight: 900,
    letterSpacing: '0.15em',
    textTransform: 'uppercase',
  },
  logoPrimary: { color: '#FF2E63' },
  logoSecondary: { color: '#08D9D6' },
  createBtn: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.4rem',
    backgroundColor: 'transparent',
    border: '1px solid #08D9D6',
    color: '#08D9D6',
    padding: '0.5rem 1.2rem',
    borderRadius: '8px',
    fontSize: '0.78rem',
    fontWeight: 700,
    cursor: 'pointer',
    letterSpacing: '0.08em',
    textTransform: 'uppercase',
  },
};
