import { colors, fontSize, fontWeight, borderRadius, zIndex } from '../../styles/tokens';

export const styles = {
  ticket: {
    width: '100%',
    display: 'flex',
    borderRadius: borderRadius.xxl,
    overflow: 'hidden',
    position: 'relative',
    boxShadow: '0 30px 80px rgba(0,0,0,0.7), 0 0 0 1px rgba(255,255,255,0.07)',
  },

  stub: {
    flexShrink: 0,
    width: '110px',
    backgroundColor: colors.primary,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    padding: '32px 16px',
    gap: '6px',
    position: 'relative',
    zIndex: zIndex.raised,
  },
  stubDate: {
    fontSize: fontSize.xl9,
    fontWeight: fontWeight.black,
    color: colors.textWhite,
    lineHeight: 1,
  },
  stubYear: {
    fontSize: fontSize.base,
    color: colors.whiteSoft,
    fontWeight: fontWeight.semibold,
  },
  stubDivider: {
    width: '40px',
    height: '1px',
    backgroundColor: colors.whiteMuted,
    margin: '10px 0',
  },
  stubSeat: {
    fontSize: fontSize.xl7,
    fontWeight: fontWeight.black,
    color: colors.textWhite,
  },
  stubSeatLabel: {
    fontSize: fontSize.xs,
    color: colors.whiteLight,
    textAlign: 'center',
    lineHeight: 1.4,
    textTransform: 'uppercase',
    letterSpacing: '1.3px',
  },

  perforation: {
    flexShrink: 0,
    width: '20px',
    backgroundColor: colors.bgCard,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    position: 'relative',
    zIndex: zIndex.raised,
  },
  circleTop: {
    width: '20px',
    height: '20px',
    borderRadius: borderRadius.circle,
    backgroundColor: colors.bgBase,
    flexShrink: 0,
    marginTop: '-1px',
  },
  dashedLine: {
    flex: 1,
    borderLeft: '2px dashed rgba(255,255,255,0.1)',
  },
  circleBottom: {
    width: '20px',
    height: '20px',
    borderRadius: borderRadius.circle,
    backgroundColor: colors.bgBase,
    flexShrink: 0,
    marginBottom: '-1px',
  },

  body: {
    flex: 1,
    backgroundColor: colors.bgCard,
    padding: '32px 32px 24px',
    display: 'flex',
    flexDirection: 'column',
    gap: '16px',
    position: 'relative',
    zIndex: zIndex.raised,
  },
  bodyTop: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  genre: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: '2.9px',
    textTransform: 'uppercase',
    color: colors.textSecondary,
  },
  badge: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    letterSpacing: '1.6px',
    textTransform: 'uppercase',
    backgroundColor: colors.primaryBg,
    color: colors.primary,
    border: `1px solid ${colors.primaryBorder}`,
    borderRadius: borderRadius.full,
    padding: '4px 12px',
  },
  title: {
    fontSize: fontSize.xl10,
    fontWeight: fontWeight.black,
    color: colors.textPrimary,
    lineHeight: 1.1,
    letterSpacing: '-0.02em',
    margin: 0,
  },
  metaRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
    marginTop: '4px',
  },
  metaItem: {
    display: 'flex',
    flexDirection: 'column',
    gap: '3px',
  },
  metaLabel: {
    fontSize: fontSize.xs,
    fontWeight: fontWeight.bold,
    letterSpacing: '2.4px',
    textTransform: 'uppercase',
    color: colors.textSecondary,
  },
  metaValue: {
    fontSize: fontSize.lg,
    fontWeight: fontWeight.semibold,
    color: colors.textPrimary,
  },

  ticketFooter: {
    borderTop: `1px solid ${colors.borderSubtle}`,
    paddingTop: '16px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: '16px',
    marginTop: 'auto',
  },
  qrWrap: {
    backgroundColor: colors.textWhite,
    padding: '10px',
    borderRadius: borderRadius.lg,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ticketNumber: {
    fontSize: fontSize.sm,
    fontWeight: fontWeight.bold,
    letterSpacing: '2.9px',
    color: colors.textSecondary,
    textTransform: 'uppercase',
  },
  scanHint: {
    fontSize: fontSize.xs,
    color: colors.textSecondary,
    letterSpacing: '1.6px',
    textTransform: 'uppercase',
    textAlign: 'right',
    maxWidth: '180px',
    lineHeight: 1.4,
  },
};
